// Code generated by "go generate ./..."; DO NOT EDIT.
//
// Source:  https://www.unicode.org/Public/emoji/latest/emoji-test.txt
// Unicode: emoji 17.0

package emojis

// The variants an emoji can be styled with. Skin tones come first and stay
// contiguous so that isSkinTone is a range check.
const (
	noVariant Variant = iota
	// light skin tone
	LightSkinTone
	// medium-light skin tone
	MediumLightSkinTone
	// medium skin tone
	MediumSkinTone
	// medium-dark skin tone
	MediumDarkSkinTone
	// dark skin tone
	DarkSkinTone
	// red hair
	RedHair
	// curly hair
	CurlyHair
	// white hair
	WhiteHair
	// blond hair
	BlondHair
	// bald
	Bald
	// beard
	Beard
)

const (
	firstSkinTone = LightSkinTone
	lastSkinTone  = DarkSkinTone
	lastVariant   = Beard
)

// variantTokens holds the CLDR name of each variant, indexed by its value.
var variantTokens = [...]string{
	noVariant:           "",
	LightSkinTone:       "light skin tone",
	MediumLightSkinTone: "medium-light skin tone",
	MediumSkinTone:      "medium skin tone",
	MediumDarkSkinTone:  "medium-dark skin tone",
	DarkSkinTone:        "dark skin tone",
	RedHair:             "red hair",
	CurlyHair:           "curly hair",
	WhiteHair:           "white hair",
	BlondHair:           "blond hair",
	Bald:                "bald",
	Beard:               "beard",
}
